### ISSUE TITLE
Python version for more flexibility?

### ISSUE THREAD

**Issue by thaikolja** [averrois/ToWebp#1]
Hi,

First off, it's a nice and simple script that works very well.

However, have you considered doing it in Python? It'd give you a lot more fine-tuning options and also valuable feedback for users (`-h` and `man`). By adding a shebang to Python and making it executable, like you're doing now, it'd run just like a bash script.

What do you think?

**Edit:** I'm sorry, I couldn't post this anywhere else, so I had to open it as a ticket.

**Comment by theurzil** [comment]
No its an amazing idea, I will try it of course, just to you knw why this tool is made at the first place, its just simple tool for a optimizing images to webp format, please if u have time read this post so that the general idea behind this 
https://www.reddit.com/r/vuejs/comments/1cruq2n/simple_bash_script_to_convert_images_to_webp/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by theurzil** [comment]
thanks for the addition I really appreciate the time and effort for your comment, keep up the hard work

**Comment by thaikolja** [comment]
I read the post, that's where I'm coming from ;) So I just wanted to polish it up a little bit since I haven't used bash in years. Thanks for accepting my merge.

**Comment by theurzil** [comment]
Thank for you contribution ....
